### ISSUE TITLE
Simplify User Input for Relationship type (SPRINT 3)

### ISSUE THREAD

**Issue by sevenfingas** [mucsci-students/2022fa-420-JAMBL#131]
When a user adds or change a relationship type simplify the necessary user input
 
 - [x] change the type enum to reflect (AGGR , INHE, COMP, REAL)
 - [x] update help so user will know the proper inputs
 - [x] checks string at each user input so if input is wrong process stops immediately

 
 - Primary: @mention
 - Secondary: @mention
 - Size: 1
 - Actual Size: 3
 - Actual Time:  4hr

**Comment by m-s1621** [comment]
had to change all the gui relationship methods
