### ISSUE TITLE
Create Field Class

### ISSUE THREAD

**Issue by sevenfingas** [mucsci-students/2022fa-420-JAMBL#45]
Add functions to set and get Name and Type of Field. Also add constructor and inistialize variables

- [x] Create Constructor (String Name ,  String Type)
- [x] String Name   
- [x] String Return Type
- [x] Set Name
- [x] Get Name
- [x] Set Type
- [x] Get Type

 Could even link or reference other tasks!

Primary: @mention

Secondary: @mention

Size: 2

Actual Size: (fib number after completion)

Actual Time: (in minutes or hours -- after completion)

**Comment by Jn-Mw-Sk** [comment]
Field class created
